Repository kubevirt/common-templates, pull requests merged in 2019-07, with the labels that each got.

#75 add windows 2019 stdci test
  automation/check-patch.windows2019.mounts
  automation/check-patch.windows2019.packages
  automation/check-patch.windows2019.sh
  automation/test-windows.sh
  automation/test.sh
  stdci.yaml
Labels: size/S

#74 templates: add versioning information
  .travis.yml
  makefile
  revision.sh
  templates/_linux.yaml
  templates/centos6.tpl.yaml
  templates/centos7.tpl.yaml
  templates/fedora.tpl.yaml
  templates/opensuse.tpl.yaml
  templates/rhel6.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/ubuntu.tpl.yaml
  templates/win2k12r2.tpl.yaml
  version.sh
Labels: size/M

#81 Add Windows Server 2016 and 2019 templates
  templates/win2k12r2.tpl.yaml
Labels: size/XS
