Repository kubevirt/common-templates, pull requests merged in 2019-10, with the labels that each got.

#96 Refactoring of travis tests
  .travis.yml
  makefile
  travis_ci/test.sh
  travis_ci/test_syntax.sh
Labels: dco-signoff: yes, size/L

#97 Released templates are automaticaly pushed to ssp operator.
  .travis.yml
  travis_ci/release-templates-ssp-operator.sh
Labels: dco-signoff: yes, size/M

#99 Add Fedora 29, Fedora 30 and RHEL 7.7 to the list of guest OSes
  generate-templates.yaml
Labels: dco-signoff: yes, size/XS

#101 add support for rhel8.1
  generate-templates.yaml
  osinfo-db-override/os/redhat.com/rhel-8.1.xml
Labels: dco-signoff: yes, size/M

#102 Fix deployment key encryption to use with travis-ci.com
  .travis.yml
  ssp-operator-deploy-key.enc
Labels: dco-signoff: yes, size/XS
