Repository kubevirt/common-templates, pull requests merged in 2020-10, with the labels that each got.

#239 Add sign-off to the release script
  travis_ci/release-templates-ssp-operator.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#247 Fix typo in the username description
  templates/_linux.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#252 update regex in script which checks if vm is alive in test
  automation/connect_to_rhel_console.exp
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#253 remove log command and replaced by while loop
  automation/test-linux.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#254 add support for rhel in test
  automation/test-linux.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#255 fix wrong url in test
  automation/test-linux.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#242 Generate additional Windows Server templates specific to Windows 2k12 R2, Windows 2k16 and Windows 2k19
  .travis.yml
  automation/test-windows.sh
  generate-templates.yaml
  templates/deprecated-windows.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
  travis_ci/test_duplicate_templates.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#272 [release-v0.12] Generate additional Windows Server templates specific to Windows server editions 2k12…
  .travis.yml
  automation/test-windows.sh
  generate-templates.yaml
  templates/deprecated-windows.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
  travis_ci/test_duplicate_templates.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#276 add dockerfile which will be used for openshift ci
  builder/Dockerfile
Labels: dco-signoff: yes, release-note-none, size/S

#277 Updated the fedora image
  travis_ci/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#256 Add a new template label to define a default variant for each OS
  .travis.yml
  generate-templates.yaml
  templates/_linux.yaml
  templates/deprecated-windows.tpl.yaml
  templates/win2k12r2-deprecated.tpl.yaml
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
  travis_ci/test_defaults.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#279 README: Fix typos in the CentOS entries
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS
