Repository kubevirt/common-templates, pull requests merged in 2020-09, with the labels that each got.

#188 Dockerfile: set permissions on /etc/passwd file
  builder/Dockerfile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#168 add new SRCPVCNAME and SRCPVCNAMESPACE params
  templates/_linux.yaml
  templates/windows.tpl.yaml
  templates/windows10.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#189 remove command to copy connect_to_rhel_console.exp script
  automation/test-rhel.sh
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#190 replace apps/v1beta1 with apps/v1 for template validator
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#191 fix sed command
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#192 disable template validator
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#193 add qemu package to dockerfile
  automation/test-rhel.sh
  automation/test.sh
  builder/Dockerfile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#194 remove chown command
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#195 added namespace in PV and PVC
  automation/test.sh
  create-minikube-pvc.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#196 change default PVC namespace
  templates/_linux.yaml
  templates/windows.tpl.yaml
  templates/windows10.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#197 update test
  automation/connect_to_rhel_console.exp
  automation/test-rhel.sh
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#178 Update validation documentation
  templates/VALIDATION.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#198 replace variables
  automation/test-rhel.sh
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#199 add namespace to local template name command
  automation/test-rhel.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#200 add oc project kubevirt command
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#201 fix kubevirt version
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#202 increase vm timeout
  automation/test-rhel.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#204 move debug lines
  automation/test-rhel.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#205 disable dynamic provisioning in pvc
  create-minikube-pvc.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#206 add storageClassName
  create-minikube-pvc.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#207 move image folder
  automation/test.sh
  builder/Dockerfile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#208 added cdi
  automation/test-rhel.sh
  automation/test.sh
  builder/Dockerfile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#209 add expect to dockerfile
  builder/Dockerfile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#210 replace expect script with virtctl console command
  automation/test-rhel.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#211 remove expect package
  builder/Dockerfile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#213 Add a parameter for randomized password
  .gitignore
  generate-templates.yaml
  templates/_linux.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#224 Add default cloud users to cloud-init
  generate-templates.yaml
  templates/_linux.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#227 Add the Major Release of an OS to every template
  generate-templates.yaml
  templates/_linux.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#235 Fix validation for disks
  templates/VALIDATION.md
  templates/win2k12r2-deprecated.tpl.yaml
  templates/windows.tpl.yaml
  templates/windows10.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#233 Removed all OS labels from deprecated template
  templates/LABELS.md
  templates/win2k12r2-deprecated.tpl.yaml
  travis_ci/validate-min-memory-consistency.py
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
