Repository kubevirt/common-templates, pull requests merged in 2020-02, with the labels that each got.

#125 rename win2k12r2 template to windows
  README.md
  automation/test-windows.sh
  generate-templates.yaml
  templates/win2k12r2-deprecated.tpl.yaml
  templates/windows.tpl.yaml
Labels: dco-signoff: yes, size/L

#126 increased PV size and timeout for windows test
  .travis.yml
  automation/test-windows.sh
  automation/test.sh
Labels: dco-signoff: yes, size/M

#128 add new windows 10 template.
  automation/test-windows.sh
  generate-templates.yaml
  templates/windows10.tpl.yaml
Labels: dco-signoff: yes, size/L

#129 Removed tiny RHEL8 template
  automation/test-rhel.sh
  generate-templates.yaml
Labels: dco-signoff: yes, size/XS

#134 Revert #129
  automation/test-rhel.sh
  generate-templates.yaml
Labels: dco-signoff: yes, size/XS

#135 increased minimum required memory for tiny rhel 8 template
  generate-templates.yaml
Labels: dco-signoff: yes, size/XS

#136 remove win 10 label from windows template
  automation/test-windows.sh
  generate-templates.yaml
  templates/windows.tpl.yaml
Labels: dco-signoff: yes, size/XS
