Repository kubevirt/common-templates, pull requests merged in 2020-11, with the labels that each got.

#283 enable Hyper-V flags
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#284 Drop major verison from PVC names of community OSs
  generate-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#287 [Bugfix] Locked the version of the deprecated templates
  automation/test_defaults.sh
  automation/test_duplicate_templates.sh
  automation/unit-tests.sh
  templates/deprecated-windows.tpl.yaml
  templates/win2k12r2-deprecated.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#290 [release-v0.12] [Bugfix] Lock deprecated versions
  templates/deprecated-windows.tpl.yaml
  templates/win2k12r2-deprecated.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#291 Release automation for new operator
  .travis.yml
  ssp-new-operator-deploy-key.enc
  ssp-new-operator-deploy-key.pub
  travis_ci/release-templates-ssp-operator.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#288 Add annotations for VirtualMachines
  templates/_linux.yaml
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S
