Repository kubevirt/common-templates, pull requests merged in 2020-04, with the labels that each got.

#144 hardcode kubevirt version to v0.27.0
  .gitignore
  .travis.yml
  automation/test-rhel.sh
  automation/test.sh
  versionsrc
Labels: dco-signoff: yes, size/M

#143 Hide VM templates from the developer catalog
  templates/centos6.tpl.yaml
  templates/centos7.tpl.yaml
  templates/fedora.tpl.yaml
  templates/opensuse.tpl.yaml
  templates/rhel6.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/ubuntu.tpl.yaml
  templates/win2k12r2-deprecated.tpl.yaml
  templates/windows.tpl.yaml
  templates/windows10.tpl.yaml
Labels: dco-signoff: yes, size/S

#142 Fix rhel8 description
  generate-templates.yaml
  templates/rhel8.tpl.yaml
Labels: dco-signoff: yes, size/S

#141 change name.os.template.kubevirt.io annotation
  templates/_linux.yaml
Labels: dco-signoff: yes, size/XS

#146 Remove 'VM' postfix from linux operating systems
  templates/_linux.yaml
Labels: dco-signoff: yes, size/XS
