Repository kubevirt/common-templates, pull requests merged in 2020-08, with the labels that each got.

#167 Added OWNERS file
  OWNERS
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#164 increase terminationGracePeriodSeconds to 30 seconds
  automation/test.sh
  templates/README.md
  templates/_linux.yaml
  templates/centos6.tpl.yaml
  templates/centos7.tpl.yaml
  templates/centos8.tpl.yaml
  templates/fedora.tpl.yaml
  templates/opensuse.tpl.yaml
  templates/rhel6.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/rhel8.tpl.yaml
  templates/ubuntu.tpl.yaml
  templates/win2k12r2-deprecated.tpl.yaml
  templates/windows.tpl.yaml
  templates/windows10.tpl.yaml
  travis_ci/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#169 add github templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#171 update makefile
  makefile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#172 install required packages
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#173 add sudo
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#174 add builder image for openshift ci
  automation/test.sh
  builder/Dockerfile
  makefile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#175 add install commands
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#176 add sudo
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#177 add debug commands
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#179 add docker handling commands
  automation/test.sh
  builder/Dockerfile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#180 replaced docker command with oc solution
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#181 add namespace
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#166 Removed flavor/size labels from the deprecated windows template
  templates/win2k12r2-deprecated.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#182 remove oc command which deploys common-template builder
  automation/test.sh
  builder/Dockerfile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#183 add findutils package
  builder/Dockerfile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#184 add user UID into dockerfile
  builder/Dockerfile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#185 remove user UID
  builder/Dockerfile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed
