Repository kubevirt/common-templates, pull requests merged in 2020-05, with the labels that each got.

#148 Fix BZ 1813198 - change recommended windows bus to sata
  templates/win2k12r2-deprecated.tpl.yaml
  templates/windows.tpl.yaml
  templates/windows10.tpl.yaml
Labels: dco-signoff: yes, ok-to-test, size/S

#150 Fix for Issue #145 Wrong display name for Centos 7 templates
  generate-templates.yaml
  osinfo-db-override/os/centos.org/centos-8.0.xml
  templates/centos8.tpl.yaml
Labels: dco-signoff: yes, size/M

#151 Use python packages from virtenv
  .travis.yml
Labels: dco-signoff: yes, size/S

#153 updated requested memory for centos8 desktop/server and ubuntu tiny template
  generate-templates.yaml
Labels: dco-signoff: yes, size/XS

#152 remove conroe cpu model from ubuntu template
  generate-templates.yaml
  templates/ubuntu.tpl.yaml
Labels: dco-signoff: yes, size/XS

#149 Add check for min memory consistency in generated templates
  .travis.yml
  travis_ci/test_syntax.sh
  travis_ci/validate-min-memory-consistency.py
Labels: dco-signoff: yes, ok-to-test, size/M

#154 Align processed VM's 'vm.kubevirt.io/template' label with template's name (include the tempalte's version)
  templates/_linux.yaml
  templates/centos6.tpl.yaml
  templates/centos7.tpl.yaml
  templates/centos8.tpl.yaml
  templates/fedora.tpl.yaml
  templates/opensuse.tpl.yaml
  templates/rhel6.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/rhel8.tpl.yaml
  templates/ubuntu.tpl.yaml
  templates/win2k12r2-deprecated.tpl.yaml
  templates/windows.tpl.yaml
  templates/windows10.tpl.yaml
Labels: dco-signoff: yes, size/M
