Repository kubevirt/common-templates, pull requests merged in 2020-07, with the labels that each got.

#160 updated README.md file.
  README.md
Labels: dco-signoff: yes, size/S

#159 enable tablet device for windows server editions
  generate-templates.yaml
Labels: dco-signoff: yes, size/XS

#147 Integrate template validator in test suite
  .travis.yml
  automation/test-rhel.sh
  automation/test-windows.sh
  automation/test.sh
  travis_ci/test.sh
Labels: dco-signoff: yes, size/L

#163 Changed the ssp-operator owner to the kubevirt org
  .travis.yml
Labels: dco-signoff: yes, size/XS

#161 Ignore disk validation if there are no disks
  templates/win2k12r2-deprecated.tpl.yaml
  templates/windows.tpl.yaml
  templates/windows10.tpl.yaml
Labels: dco-signoff: yes, size/XS

#165 remove windows 2008 labels from windows templates
  templates/LABELS.md
  templates/win2k12r2-deprecated.tpl.yaml
  templates/windows.tpl.yaml
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/S
