Repository kubevirt/common-templates, pull requests merged in 2020-01, with the labels that each got.

#120 Update Templates Memory Requests to Power-2-Based Values
  generate-templates.yaml
Labels: dco-signoff: yes, size/L

#119 add json validation for validation in common-templates
  .travis.yml
  travis_ci/check-validations.py
  travis_ci/test_syntax.sh
Labels: dco-signoff: yes, size/M

#124 changed download URL for centos8 image
  travis_ci/test.sh
Labels: dco-signoff: yes, size/XS
