Repository kubevirt/common-templates, pull requests merged in 2021-12, with the labels that each got.

#386 fix github actions release script
  .github/workflows/release.yaml
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm

#387 Change user fork in github actions
  .github/workflows/release.yaml
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm

#384 Add a RHEL8 template targeting SAP HANA as workload
  automation/test-linux.sh
  automation/test.sh
  automation/unit-tests.sh
  automation/validate-min-memory-consistency.py
  generate-templates.yaml
  templates/rhel8.saphana.tpl.yaml
Labels: size/L, release-note, dco-signoff: yes, lgtm, approved

#390 Revert parameter names back to SRC_PVC_NAME and SRC_PVC_NAMESPACE
  README.md
  automation/test-linux.sh
  automation/test-windows.sh
  automation/unit-tests.sh
  automation/validate-pvc-name-stability.py
  templates/README.md
  templates/centos6.tpl.yaml
  templates/centos7.tpl.yaml
  templates/centos8.tpl.yaml
  templates/fedora.tpl.yaml
  templates/opensuse.tpl.yaml
  templates/rhel6.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/rhel8.tpl.yaml
  templates/rhel9.tpl.yaml
  templates/ubuntu.tpl.yaml
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#389 remove generation of sap hana template
  generate-templates.yaml
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#392 Add a condition to saphana ansible task to disable it
  generate-templates.yaml
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#388 Add displayName for SAP HANA template parameters
  templates/rhel8.saphana.tpl.yaml
Labels: release-note, size/S, dco-signoff: yes, ok-to-test, lgtm

#396 Enable the generation of the rhel8.saphana
  generate-templates.yaml
Labels: release-note, size/XS, dco-signoff: yes, lgtm
