Repository kubevirt/common-templates, pull requests merged in 2021-03, with the labels that each got.

#323 Add support for multiqueue networking for high performance Windows templates
  generate-templates.yaml
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#331 Update release script with new location of Version constant in SSP operator
  .github/workflows/release.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#322 Print templates to stdout in CI
  automation/unit-tests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#332 Explicitly set the version of the bundle when generating it for a release
  .github/workflows/release.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#334 Modify automation tests to support both K8s and OC environment
  .github/workflows/release.yaml
  .travis.yml
  README.md
  automation/test-linux.sh
  automation/test-windows.sh
  automation/test.sh
  automation/unit-tests.sh
  dvtemplates/fedora_new_image.sh
  generate-templates.yaml
  ssp-new-operator-deploy-key.enc
  ssp-new-operator-deploy-key.pub
  ssp-operator-deploy-key.enc
  ssp-operator-deploy-key.pub
  templates/LABELS.md
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
  travis_ci/release-templates-ssp-operator.sh
Labels: dco-signoff: no, do-not-merge/release-note-label-needed, size/L

#333 Include full semver in release manifests
  version.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#336 Modify script to suport both K8s and OC environment
  automation/test-linux.sh
  automation/test.sh
  dvtemplates/fedora_new_image.sh
  version.sh
Labels: dco-signoff: no, do-not-merge/release-note-label-needed, size/L

#337 Modify script to change docker registry
  dvtemplates/fedora_new_image.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#339 Revert back to using oc client
  automation/test-linux.sh
  automation/test.sh
  dvtemplates/fedora_new_image.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#341 [backport] fix hardcoded fedora name in annotations
  templates/fedora.tpl.yaml
Labels: dco-signoff: yes, lgtm, release-note-none, size/XS

#342 Revert back to labeling only the worker nodes for high performace VM tests
  automation/test.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#307 Add a script to check and download the latest fedora image and build …
  automation/test-linux.sh
  automation/test-windows.sh
  automation/test.sh
  dvtemplates/Dockerfile
  dvtemplates/fedora_new_image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
