Repository kubevirt/common-templates, pull requests merged in 2021-04, with the labels that each got.

#346 Cdi
  automation/test-linux.sh
  automation/test-windows.sh
  automation/test.sh
  dvtemplates/fedora_new_image.sh
Labels: dco-signoff: no, release-note-none, size/L

#343 Remove any spaces when collecting the Fedora version from the Fedora repository
  dvtemplates/fedora_new_image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#340 Update VM API version from v1alpha3 to v1
  templates/VALIDATION.md
  templates/centos6.tpl.yaml
  templates/centos7.tpl.yaml
  templates/centos8.tpl.yaml
  templates/fedora.tpl.yaml
  templates/opensuse.tpl.yaml
  templates/rhel6.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/rhel8.tpl.yaml
  templates/ubuntu.tpl.yaml
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#348 Add periodic job support for CentOS cdi image.
  automation/test-linux.sh
  automation/test.sh
  dvtemplates/centos/Dockerfile
  dvtemplates/centos/centos_new_image.sh
  dvtemplates/fedora/Dockerfile
  dvtemplates/fedora/fedora-datavolume-template.yaml
  dvtemplates/fedora/fedora_new_image.sh
  templates/VALIDATION.md
  templates/centos6.tpl.yaml
  templates/centos7.tpl.yaml
  templates/centos8.tpl.yaml
  templates/fedora.tpl.yaml
  templates/opensuse.tpl.yaml
  templates/rhel6.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/rhel8.tpl.yaml
  templates/ubuntu.tpl.yaml
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: dco-signoff: yes, release-note-none, size/L

#347 Use the Fedora Release url - https://getfedora.org/releases.json to identify the latest releases, and their image download links.
  dvtemplates/fedora_new_image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#350 Merge pull request #348 from shwetaap/cdi
  automation/test-linux.sh
  dvtemplates/build_k8s_cluster.sh
  dvtemplates/centos/centos_new_image.sh
  dvtemplates/new_cdi_image.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#352 Modify script to support both CentOS and Fedora periodic job
  dvtemplates/build_k8s_cluster.sh
  dvtemplates/new_cdi_image.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#357 Disable testing of high performance templates.
  automation/test-linux.sh
  automation/test-windows.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#353 Fix os/flavor/workload annotations location
  templates/centos6.tpl.yaml
  templates/centos7.tpl.yaml
  templates/centos8.tpl.yaml
  templates/fedora.tpl.yaml
  templates/opensuse.tpl.yaml
  templates/rhel6.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/rhel8.tpl.yaml
  templates/ubuntu.tpl.yaml
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#358 Modify script to support both CentOS and Fedora periodic job
  dvtemplates/build_k8s_cluster.sh
  dvtemplates/centos/Dockerfile
  dvtemplates/centos/centos_new_image.sh
  dvtemplates/new_cdi_image.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#351 Periodic job for creating a container disk image for the latest CentOS Version
  dvtemplates/Dockerfile
  dvtemplates/build_k8s_cluster.sh
  dvtemplates/centos8/Dockerfile
  dvtemplates/fedora/Dockerfile
  dvtemplates/fedora_new_image.sh
  dvtemplates/new_cdi_image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#338 add support for stimer direct to windows templates
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S
