Repository kubevirt/common-templates, pull requests merged in 2021-08, with the labels that each got.

#368 Add golang to the builder container for the tests
  builder/Dockerfile
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved

#369 update rhel 9 template description
  templates/rhel9.tpl.yaml
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#370 change datavolume api version to v1
  templates/centos6.tpl.yaml
  templates/centos7.tpl.yaml
  templates/centos8.tpl.yaml
  templates/fedora.tpl.yaml
  templates/opensuse.tpl.yaml
  templates/rhel6.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/rhel8.tpl.yaml
  templates/rhel9.tpl.yaml
  templates/ubuntu.tpl.yaml
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: release-note, size/S, dco-signoff: yes, lgtm
