Repository kubevirt/common-templates, pull requests merged in 2021-01, with the labels that each got.

#302 Adopt RHEL6 and Centos 6 templates to new libvirt/QEMU changes
  templates/centos6.tpl.yaml
  templates/rhel6.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#300 add support for scsi disk bus in windows validation
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#304 update base image for openshiftci
  builder/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#308 add python3-openshift to builder
  builder/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#310 Add emulator thread
  automation/test-linux.sh
  generate-templates.yaml
  templates/fedora.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/rhel8.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#312 Add a script to check and download the latest fedora image
  dvtemplates/Dockerfile
  dvtemplates/fedora-datavolume-template.yaml
  dvtemplates/fedora_new_image.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#311 fix hard coded fedora name in annotations
  templates/fedora.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#298 validate pvc name and namespace stability across upgrades
  automation/unit-tests.sh
  automation/validate-pvc-name-stability.py
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#305 Centos 6 and RHEL 6 to use virtio bus for network and storage by default
  automation/test-linux.sh
  templates/centos6.tpl.yaml
  templates/rhel6.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S
