Repository kubevirt/common-templates, pull requests merged in 2021-02, with the labels that each got.

#318 Fixed hard-coded values in Ubuntu template
  templates/ubuntu.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#317 Add Windows high performance templates
  automation/test-windows.sh
  generate-templates.yaml
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#315 Expand I/O threads support for high performance templates
  templates/fedora.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/rhel8.tpl.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#325 roll back to previous version version of CDI
  automation/test.sh
Labels: dco-signoff: yes, lgtm, release-note-none, size/XS

#327 Fedora CDI creation
  automation/test-linux.sh
  automation/test-windows.sh
  automation/test.sh
  generate-templates.yaml
  templates/fedora.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/rhel8.tpl.yaml
  templates/ubuntu.tpl.yaml
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#328 Remove "Contenttype" Fix for CDI Issue
  automation/test-linux.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#320 Bumped version of Ubuntu LTS from 18.04 to 20.04
  README.md
  generate-templates.yaml
  templates/LABELS.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/XS

#324 add test_id for pvc stability test
  automation/unit-tests.sh
Labels: approved, dco-signoff: yes, release-note-none, size/XS

#330 Improve tests stability
  automation/test-linux.sh
  automation/test-windows.sh
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#329 Migrate TravisCI jobs to Github Actions
  .github/workflows/release.yaml
  .travis.yml
  ssp-new-operator-deploy-key.enc
  ssp-new-operator-deploy-key.pub
  ssp-operator-deploy-key.enc
  ssp-operator-deploy-key.pub
  travis_ci/release-templates-ssp-operator.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
