Repository kubevirt/common-templates, pull requests merged in 2022-01, with the labels that each got.

#394 Update openshift mirror URL to working one
  builder/Dockerfile
  dvtemplates/new_cdi_image.sh
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved

#397 Change recommended disk image url 32 -> 34
  templates/fedora.tpl.yaml
Labels: size/XS, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#400 highperformance windows templates now uses virtio for storage
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#401 Adjust hana template parameter details
  automation/unit-tests.sh
  templates/rhel8.saphana.tpl.yaml
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#404 Remove virtio model reference on sriov
  templates/rhel8.saphana.tpl.yaml
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved

#398 Rename parameters to DATA_SOURCE_NAME and DATA_SOURCE_NAMESPACE
  README.md
  automation/test-linux.sh
  automation/test-windows.sh
  automation/unit-tests.sh
  automation/validate-pvc-name-stability.py
  templates/README.md
  templates/centos-stream8.tpl.yaml
  templates/centos-stream9.tpl.yaml
  templates/centos6.tpl.yaml
  templates/centos7.tpl.yaml
  templates/fedora.tpl.yaml
  templates/opensuse.tpl.yaml
  templates/rhel6.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/rhel8.tpl.yaml
  templates/rhel9.tpl.yaml
  templates/ubuntu.tpl.yaml
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: size/L, release-note, dco-signoff: yes, lgtm, approved
