Repository kubevirt/common-templates, pull requests merged in 2022-10, with the labels that each got.

#485 Drop centos.org overrides
  osinfo-db-override/os/centos.org/centos-stream-8.xml
  osinfo-db-override/os/centos.org/centos-stream-9.xml
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#486 Windows 2022 template is missing vTPM and UEFI
  templates/windows2k22.tpl.yaml
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#490 Add 0xFelix to approvers
  OWNERS
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm
