Repository kubevirt/common-templates, pull requests merged in 2022-05, with the labels that each got.

#438 Add containerdisks annotation to Ubuntu template
  templates/ubuntu.tpl.yaml
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#440 Remove version information from fedora display name
  templates/fedora.tpl.yaml
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#441 bump fedora containerdisk to 36
  templates/fedora.tpl.yaml
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#447 remove legacy code, which creates container disks
  automation/test-linux.sh
  dvtemplates/build_k8s_cluster.sh
  dvtemplates/centos8/Dockerfile
  dvtemplates/fedora/Dockerfile
  dvtemplates/new_cdi_image.sh
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#442 update owners file to reflect current contributors
  OWNERS
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved

#449 Updating RHEL 9 Template name and recommended url
  templates/rhel9.tpl.yaml
Labels: release-note, size/S, dco-signoff: yes, ok-to-test, lgtm, approved

#453 [release-v0.19] Updating RHEL 9 Template name and description
  templates/rhel9.tpl.yaml
Labels: release-note, size/S, dco-signoff: yes

#452 [release-v0.16] Updating RHEL 9 Template name and description
  templates/rhel9.tpl.yaml
Labels: release-note, size/S, dco-signoff: yes, lgtm
