Repository kubevirt/common-templates, pull requests merged in 2022-04, with the labels that each got.

#431 Change docker commands into podman
  .github/workflows/release.yaml
  dvtemplates/build_k8s_cluster.sh
  dvtemplates/new_cdi_image.sh
Labels: release-note, size/S, dco-signoff: yes, ok-to-test, lgtm, approved

#433 remove sap hana template
  automation/test-linux.sh
  generate-templates.yaml
  templates/rhel8.saphana.tpl.yaml
Labels: size/L, release-note, dco-signoff: yes, lgtm, approved

#435 remove automation for sap hana template
  automation/test-linux.sh
  automation/test_containerdisk_annotations.sh
  automation/unit-tests.sh
  templates/LABELS.md
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved
