Repository kubevirt/common-templates, pull requests merged in 2022-02, with the labels that each got.

#413 Improve openSUSE template
  generate-templates.yaml
  templates/opensuse.tpl.yaml
Labels: size/L, release-note, dco-signoff: yes, needs-ok-to-test, lgtm, approved

#409 Update templates/LABELS.md
  templates/LABELS.md
Labels: size/M, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#411 Update README.md
  README.md
Labels: size/M, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#414 Add osinfo-db overrides for distributions without cloud images
  osinfo-db-override/os/centos.org/centos-stream-8.xml
  osinfo-db-override/os/centos.org/centos-stream-9.xml
  osinfo-db-override/os/opensuse.org/opensuse-15.2.xml
  osinfo-db-override/os/opensuse.org/opensuse-15.3.xml
Labels: size/M, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#412 Improve Ubuntu template
  automation/test-linux.sh
  generate-templates.yaml
  templates/ubuntu.tpl.yaml
Labels: release-note, size/S, dco-signoff: yes, ok-to-test, lgtm, approved

#415 Rename the first HD rootdisk
  templates/centos-stream8.tpl.yaml
  templates/centos-stream9.tpl.yaml
  templates/centos6.tpl.yaml
  templates/centos7.tpl.yaml
  templates/fedora.tpl.yaml
  templates/opensuse.tpl.yaml
  templates/rhel6.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/rhel8.tpl.yaml
  templates/rhel9.tpl.yaml
  templates/ubuntu.tpl.yaml
  templates/windows10.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
Labels: size/M, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#406 Add annotations for containerdisks and import URLs
  generate-templates.yaml
  templates/centos-stream8.tpl.yaml
  templates/centos-stream9.tpl.yaml
  templates/centos7.tpl.yaml
  templates/fedora.tpl.yaml
  templates/opensuse.tpl.yaml
  templates/rhel8.tpl.yaml
  templates/rhel9.tpl.yaml
  templates/ubuntu.tpl.yaml
Labels: size/M, release-note, dco-signoff: yes, ok-to-test, lgtm, approved

#418 Cleanup builder/Dockerfile
  builder/Dockerfile
Labels: release-note-none, size/S, dco-signoff: yes, ok-to-test, lgtm, approved

#420 Download oc binary from new location and readd intltool
  builder/Dockerfile
Labels: size/XS, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#421 Follow redirects when downloading oc and yq
  builder/Dockerfile
Labels: size/XS, release-note-none, dco-signoff: yes, needs-ok-to-test

#419 Improve existing unit tests
  automation/test_defaults.sh
  automation/test_duplicate_templates.sh
Labels: size/M, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#417 Add containerdisk annotations test
  automation/test_containerdisk_annotations.sh
  automation/unit-tests.sh
Labels: size/M, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#422 Update osinfo-db on schedule
  .github/workflows/update-osinfo-db.yaml
  makefile
Labels: size/M, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved
