Repository kubevirt/common-templates, pull requests merged in 2023-08, with the labels that each got.

#545 Annotate Windows Server 2012 as deprecated
  automation/test-windows.sh
  templates/windows2k12.tpl.yaml
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#546 feat: add podman to builder image
  builder/Dockerfile
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm

#543 feat: replace vm.spec.template.spec.domain.resources.requests.memory …
  automation/validate-min-memory-consistency.py
  templates/README.md
  templates/VALIDATION.md
  templates/centos-stream8.tpl.yaml
  templates/centos-stream9.tpl.yaml
  templates/centos6.tpl.yaml
  templates/centos7.tpl.yaml
  templates/fedora.tpl.yaml
  templates/opensuse.tpl.yaml
  templates/rhel7.tpl.yaml
  templates/rhel8.tpl.yaml
  templates/rhel9.tpl.yaml
  templates/ubuntu.tpl.yaml
  templates/windows10.tpl.yaml
  templates/windows11.tpl.yaml
  templates/windows2k12.tpl.yaml
  templates/windows2k16.tpl.yaml
  templates/windows2k19.tpl.yaml
  templates/windows2k22.tpl.yaml
Labels: size/L, release-note, dco-signoff: yes, lgtm, approved
