Repository kubevirt/common-templates, pull requests merged in 2023-01, with the labels that each got.

#502 increase timeout for windows vms in tests
  automation/test-windows.sh
Labels: release-note-none, dco-signoff: yes

#503 increase timeout for windows vms and datavolume in tests
  automation/test-windows.sh
Labels: size/XS, release-note-none, dco-signoff: yes

#505 switch to ssd storageClass in windows tests
  automation/test.sh
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved

#506 fix: improve the condition for switching storageclass in e2e test
  automation/test.sh
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved

#507 docs: remove beta from rhel 9 guest os
  README.md
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved
