Repository kubevirt/common-templates, pull requests merged in 2024-11, with the labels that each got.

#631 fix: disable efi bootloader in fedora for s390x
  templates/fedora.tpl.yaml
Labels: size/XS, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#632 fix: disable SMM on Fedora for s390x architecture
  templates/fedora.tpl.yaml
Labels: size/XS, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#633 perf: optimizes check for updated machineconfigpool
  automation/test.sh
Labels: release-note-none, size/S, dco-signoff: yes, ok-to-test, lgtm, approved

#634 fix: address failing tests on Ubuntu
  automation/test-linux.sh
Labels: size/XS, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#636 fix: increase timeout for end-to-end tests
  automation/test-linux.sh
Labels: size/XS, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#635 fix: patterns in expect script and adjust timeout/exit conditions
  automation/connect_to_rhel_console.exp
  automation/test-linux.sh
Labels: size/XS, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#638 fix: update legacy containerdisks url
  automation/test-linux.sh
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#642 feat: target archictecture as a parameter
  automation/test-linux.sh
  generate-templates.yaml
  makefile
  templates/fedora.tpl.yaml
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#643 feat: disable distributions incompatible with s390x architecture
  generate-templates.yaml
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#647 feat: s390x Ubuntu enablement
  generate-templates.yaml
  templates/ubuntu.tpl.yaml
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved

#648 fix: creation of /.ansible folder in builder dockerfile
  builder/Dockerfile
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved
