Repository kubevirt/common-templates, pull requests merged in 2024-09, with the labels that each got.

#610 fix: remove tiny size from e2e test for fedora
  automation/test-linux.sh
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm

#608 feat: enable virtctl download based on host architecture
  automation/test.sh
Labels: size/XS, release-note-none, dco-signoff: yes, ok-to-test

#612 fix: use spec.storage in DV in e2e tests
  automation/test-linux.sh
  automation/test-windows.sh
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved

#613 fix: remove call to legacy template validator
  .gitignore
  automation/test.sh
Labels: release-note-none, size/S, dco-signoff: yes, ok-to-test, lgtm, approved

#611 Windows 11: enable TPM and EFI persistence
  automation/test.sh
  templates/windows11.tpl.yaml
  templates/windows2k22.tpl.yaml
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#615 fix: add make clean
  makefile
Labels: size/XS, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#616 feat: disable Centos 6 on s390x architecture
  automation/test-linux.sh
  generate-templates.yaml
Labels: size/XS, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#617 chore: add Windows Server 2k25 template
  generate-templates.yaml
  osinfo-db-override/os/microsoft.com/win-2k25.xml
  templates/windows2k25.tpl.yaml
Labels: size/L, release-note, dco-signoff: yes, lgtm, approved

#618 fix: fix minimum requirements in win2k25 template
  osinfo-db-override/os/microsoft.com/win-2k25.xml
  templates/windows2k25.tpl.yaml
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved
