Repository kubevirt/common-templates, pull requests merged in 2024-10, with the labels that each got.

#623 fix: fedora workloads definition in function tests
  automation/test-linux.sh
Labels: size/XS, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#626 feat: add ssh client to builder image
  builder/Dockerfile
Labels: size/XS, release-note-none, dco-signoff: yes, approved

#628 README: use spec.runStrategy instead of spec.running
  templates/README.md
Labels: size/XS, release-note-none, dco-signoff: yes

#624 feat: multiarch fedora template.
  generate-templates.yaml
  templates/fedora.tpl.yaml
Labels: size/XS, release-note-none, dco-signoff: yes, ok-to-test, lgtm, approved

#621 feat!: remove centos7 and centos 8 stream templates
  README.md
  automation/test-linux.sh
  generate-templates.yaml
  templates/centos-stream8.tpl.yaml
  templates/centos7.tpl.yaml
Labels: size/L, release-note, dco-signoff: yes, lgtm
