Repository kubevirt/common-templates, pull requests merged in 2025-03, with the labels that each got.

#672 fix: Windows e2e tests
  automation/test-windows.sh
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#669 Enable arm64 builds
  .github/workflows/release.yaml
  generate-templates.yaml
  makefile
  templates/centos-stream9.tpl.yaml
  templates/fedora.tpl.yaml
  templates/rhel9.tpl.yaml
  templates/ubuntu.tpl.yaml
Labels: size/M, release-note, dco-signoff: yes, lgtm, approved

#676 chore: remove opokornyy from reviewers
  OWNERS
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved

#677 Fix release process
  makefile
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved
